### ISSUE TITLE
Cannot parse AMF: "readByte is not defined"

### ISSUE THREAD

**Issue by DoomTay** [jamesward/JSAMF#6]
I'm working on an HTML5 port of a Flash-based drawing replayer, and I'm stuck with parsing the actual AMF

```javascript
var test = new XMLHttpRequest();
test.onload = function ()
{
	console.log(decodeAMF(this.response));
}
test.open("GET", "23828-24312.amf", true);
test.overrideMimeType("text/plain; charset=x-user-defined");
test.send();
```

and an error occurs with the following trace
```
readUInt30BE file:///E:/Projects/AMFFail/amf.js:449:9
readAMF0Object file:///E:/Projects/AMFFail/amf.js:816:9
readObject file:///E:/Projects/AMFFail/amf.js:784:14
decodeAMF file:///E:/Projects/AMFFail/amf.js:62:23
test.onload file:///E:/Projects/AMFFail/index.html:18:16
```

Converting the response to an array buffer with `test.responseType = "arraybuffer";` and decoding that resulted in an object with a version of 0 and the header and messages were empty. Converting the array buffer to an Uint8Array resulted in the same error

[Here](http://web.archive.org/web/20170610154736id_/http://chat-img11.pixiv.net/001/098/830/72dd46d4/23828-24312.amf) is the AMF in question.

**Comment by jamesward** [comment]
It's been a really long time since I worked with AMF so unfortunately I won't be much help.  I vaguely remember there was debugish function in the `amf.js` lib to do like a hex dump some AMF data.  Looking at that and the AMF spec might help.

**Comment by DoomTay** [comment]
After doing some digging around, it seems the root cause is that `readBytes()` should be `this.readBytes()`. Though after fixing that, I found a different problem: the while (true) loop on line 818 runs infinitely. Setting it to breaks if the current position is bigger than the size of the data results in finally getting output, though the output is...weird. There are no messages, and the first header is messed up. Here's the first one

```
name: name: "mmand
stroke
params	
thicknessxdalpha?¶È´9Xc[...]
mustUnderstand: true
data: 1.1125369292704226e-308 
```

Probably something about the file parsing not matching the spec. I'll look into it later.

**Comment by jamesward** [comment]
I remember using an AMF dump tool a while back but I don't remember where I got it from.  That might help when digging deeper.

**Comment by DoomTay** [comment]
Okay, wow, I think I found the real reason for this weirdness: The AMFs I'm working with start off very differently from "regular" AMFs. This and one other AMF from the same project start off with the bytes `0a 0b 01 0f 63 6f 6d 6d 61 6e 64 06 0d 73 74 72 6f 6b 65 0d 70 61 72 61 6d 73 09`

So right off the bat these files do something a little different than spec. Nonetheless, the original Flash thing handles these normally, hence why I didn't think to look at the contents of the files earlier (and why I'm not writing these files off as corrupted or anything like that)

**Comment by jamesward** [comment]
I wonder if it is AMF 1 and the spec & my impl is for AMF 3?

**Comment by DoomTay** [comment]
After digging into the Flash object that makes use of these files, it looks like these are actually a series of AMF3 objects, processed via custom code.

So while `decodeAMF` would never have handled these particular files, the use of of ByteArray commands still comes in handy.
